# Gunakan image dasar PHP yang stabil
FROM php:8.2-fpm

# Label agar GitHub mengenali registry Anda
LABEL org.opencontainers.image.source=https://github.com/eka11abbie-oss/proyek-kelompok-sijayam

# Set direktori kerja
WORKDIR /app

# Copy file proyek Anda ke dalam container
COPY . .

# Expose port (biasanya 8080 untuk API)
EXPOSE 8080

# Jalankan server
CMD ["php", "-S", "0.0.0.0:8080", "-t", "public"]