version: '3.8'

services:
  backend-sijayam:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      # Product Lead
      - ./logs:/app/writable/logs

  frontend-sijayam:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    env_file:
      - .env
    volumes:
      # Frontend Developer (Bind Mount folder asset)
      - ./sijayam-app/public/asset:/usr/share/nginx/html/sijayam-app/public/asset
