FROM php:8.2-cli

RUN apt-get update && apt-get install -y \
    libicu-dev \
    && docker-php-ext-configure intl \
    && docker-php-ext-install intl mysqli pdo pdo_mysql

# [TUGAS E.1] - Menentukan variabel lingkungan database
ENV DB_HOST=localhost
ENV DB_PORT=3306

WORKDIR /app

# PERUBAHAN DI SINI: Kita arahkan Docker buat ngambil isi folder sijayam-app
COPY ./sijayam-app .

EXPOSE 8080

CMD ["php", "spark", "serve", "--host", "0.0.0.0", "--port", "8080"]