version: '3.8'

services:
  # -------------------------------------
  # SERVICE FRONTEND
  # -------------------------------------
  frontend-sijayam:
    image: ghcr.io/eka11abbie-oss/proyek-kelompok-sijayam-fe:v1.0.0
    ports:
      - "80:80"
    env_file:
      - .env
    volumes:
      - ./public/assets:/usr/share/nginx/html/assets

  # -------------------------------------
  # SERVICE BACKEND
  # -------------------------------------
  backend-sijayam:
    image: ghcr.io/eka11abbie-oss/proyek-kelompok-sijayam-be:v1.0.0
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./logs:/app/writable/logs

  # -------------------------------------
  # SERVICE DATABASE
  # -------------------------------------
  db-server:
    image: postgres:15-alpine
    environment:
      - POSTGRES_PASSWORD=rahasia
    volumes:
      - db-data:/var/lib/postgresql/data 

volumes:
  db-data: