version: '3.8'

services:
  # -------------------------------------
  # SERVICE FRONTEND
  # -------------------------------------
  frontend-sijayam:
    # TUGAS M14: Menggunakan image produksi dari GitHub Registry
    image: ghcr.io/[GANTI_DENGAN_USERNAME_GITHUB_KELOMPOK]/proyek-kelompok-sijayam-fe:v1.0.0
    ports:
      - "80:80"
    env_file:
      - .env
    volumes:
      # Bind Mount untuk aset lokal
      - ./public/assets:/usr/share/nginx/html/assets

  # -------------------------------------
  # SERVICE BACKEND
  # -------------------------------------
  backend-sijayam:
    # TUGAS M14: Menggunakan image produksi dari GitHub Registry
    image: ghcr.io/[GANTI_DENGAN_USERNAME_GITHUB_KELOMPOK]/proyek-kelompok-sijayam-be:v1.0.0
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      # Memetakan folder lokal ke kontainer menggunakan Bind Mount
      - ./logs:/app/writable/logs

  # -------------------------------------
  # SERVICE DATABASE
  # -------------------------------------
  db-server:
    image: postgres:15-alpine
    environment:
      - POSTGRES_PASSWORD=rahasia
    volumes:
      # Named Volume untuk data DB
      - db-data:/var/lib/postgresql/data 

volumes:
  # Definisi named volume global
  db-data: